/**
 * lightTrialSteps.js — Light 無料体験シーケンスの Step5〜24（文面の単一源）
 *
 * ── なぜ 24 通か ──────────────────────────────────────────────
 * 目的は「無反応の相手にも接点を作って反応を見る」こと。4 通で終わると
 * **反応が出る前に打ち切る**ことになる。一方で同じ訴求を 24 回繰り返すのは
 * ただの嫌がらせなので、**角度（angle）を分散**する。
 *
 * ── 書くときの禁止事項（`FORBIDDEN_PHRASES` と同じ方針）───────────
 * - 的中・利益の**保証**、「必ず」「絶対」「確実に」
 * - **架空の実績・数値**（実績はページへ誘導し、メールに書き写さない）
 * - 「今だけ」「残りわずか」の煽り
 * - 価格の直書き（`/pricing/` が正本）
 *
 * ── 間隔 ────────────────────────────────────────────────────
 * `delayDays` は**前の通からの日数**。無料期間 30 日の間は詰めすぎず、
 * 期間後は間隔を広げる。実際の送信間隔は `sequencePolicy` の
 * 最小間隔・頻度上限（7 日で 2 通）が上限として効く。
 *
 * ⚠️ **本番送信はしない。** 管理画面の `action=preview` で 1 通ずつ確認できる。
 */

const SITE = 'https://analytics.keiba.link';

/** 無料期間の終了日を差し込む印（`marketingEmailShell.js` が解決する） */
const EXPIRY = '{{grantExpiry}}';

/**
 * 訴求角度。**同じ角度を連続で置かない**（`sequencePolicy.pickAngle` と対応）。
 * 画面にも出すので、日本語の短い語にする。
 */
export const LIGHT_TRIAL_ANGLES = Object.freeze([
  '体験の開始', '使い方', '活用例', '中央競馬', '南関競馬', '習慣化',
  '買い目の使い方', '成績の確認', 'Premium との差', '期間の確認',
  '不安の解消', '料金の考え方', '継続の提案', '期限前', '期限後', 'comeback',
]);

/** 1 ステップぶんの共通形（`campaignCatalog` の step と同じ形） */
const step = ({
  n, delayDays, angle, name, subject, preheader, badge, headline,
  body, benefitTitle, benefitItems, ctaLabel, ctaUrl, ctaNote, footerNote,
}) => ({
  stepNumber: n,
  delayDays,
  /** 訴求角度（連投を避けるための札） */
  angle,
  name,
  subject,
  preheader,
  badge,
  headline,
  body: body.join('\n'),
  benefitTitle,
  benefitItems,
  ctaLabel,
  ctaUrl,
  ctaNote,
  ...(footerNote ? { footerNote } : {}),
  benefitType: 'free_access',
  benefitDescription: 'Lightプランの無料期間中にご覧いただける内容のご案内です',
});

/**
 * Step5〜24。**Step1〜4（`campaignCatalog.js`）の続き**。
 * 角度は 16 種を一巡してから前半へ戻す（`LIGHT_TRIAL_ANGLES` の順）。
 */
export const LIGHT_TRIAL_EXTRA_STEPS = Object.freeze([
  step({
    n: 5, delayDays: 4, angle: '活用例',
    name: '当日の見方（レース前）',
    subject: '【KEIBA Analytics】レース前に見ておくと分かりやすい順番',
    preheader: '出走前に、本命・相手・不要馬の並びをどう読むかをご案内します。',
    badge: '見方',
    headline: 'レース前に見る順番',
    body: [
      'メインレースのページは、上から順に見ていただくと読みやすくなっています。',
      '',
      '1. 本命と対抗（軸にする馬）',
      '2. 相手（買い目に入る馬）',
      '3. 抑え・不要馬（外す理由が書いてある馬）',
      '',
      'AI総合指数は馬ごとの評価値です。数字そのものより、',
      '同じレース内での並び方を見ていただくと差が分かりやすくなります。',
    ],
    benefitTitle: 'レース前の 3 分',
    benefitItems: ['本命と対抗を確認する', '相手 5 頭を確認する', '外している馬の理由を見る'],
    ctaLabel: '今日のメインレースを見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 6, delayDays: 4, angle: '中央競馬',
    name: '中央（JRA）の予想',
    subject: '【KEIBA Analytics】中央競馬（JRA）の予想について',
    preheader: '土日の中央競馬もご覧いただけます。開催が複数場のときの見方もご案内します。',
    badge: '中央競馬',
    headline: '土日は中央競馬（JRA）もご覧いただけます',
    body: [
      '当サイトは南関競馬と中央競馬（JRA）の両方を扱っています。',
      '',
      '中央は土日開催で、複数の会場が同時に行われます。',
      '会場ごとにメインレースが決まるので、見たい会場を選んでご覧ください。',
      '',
      '平日は南関競馬、土日は中央競馬という形でお使いいただけます。',
    ],
    benefitTitle: '中央競馬のページ',
    benefitItems: ['会場ごとのメインレース', 'AI総合指数と役割', '前日の買い目と結果'],
    ctaLabel: '中央競馬の予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 7, delayDays: 5, angle: '南関競馬',
    name: '南関の予想',
    subject: '【KEIBA Analytics】南関競馬（大井・船橋・川崎・浦和）について',
    preheader: '平日開催の南関競馬。会場ごとのメインレースをご覧いただけます。',
    badge: '南関競馬',
    headline: '平日は南関競馬をご覧いただけます',
    body: [
      '南関競馬は大井・船橋・川崎・浦和の 4 場で、平日にも開催があります。',
      '',
      '中央競馬が休みの平日でも予想をご覧いただけるので、',
      '「見る日」を増やしたい方にはこちらが中心になります。',
      '',
      '会場ごとにメインレースが決まります。開催のある会場だけが表示されます。',
    ],
    benefitTitle: '南関のページ',
    benefitItems: ['開催中の会場が並ぶ', '会場ごとのメインレース', '前日の結果との突き合わせ'],
    ctaLabel: '南関の予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 8, delayDays: 5, angle: '習慣化',
    name: '見るタイミング',
    subject: '【KEIBA Analytics】見るタイミングを決めておくと続きます',
    preheader: '前日の夜か当日の朝。どちらかに決めておくと迷いません。',
    badge: '続け方',
    headline: '「いつ見るか」を決めておく',
    body: [
      '予想は開催前に公開しています。',
      '',
      '前日の夜にまとめて見る方と、当日の朝に見る方が多いようです。',
      'どちらかに決めておくと、見忘れが減ります。',
      '',
      '見られなかった日があっても、翌日の結果ページで答え合わせができます。',
    ],
    benefitTitle: '決めておくこと',
    benefitItems: ['前日の夜か当日の朝か', 'どの会場を見るか', '結果をいつ確認するか'],
    ctaLabel: '予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 9, delayDays: 5, angle: '買い目の使い方',
    name: '買い目の考え方',
    subject: '【KEIBA Analytics】買い目をそのまま使わない場合の考え方',
    preheader: '本命→相手5頭の馬単5点。ご自身の見立てと合わせる方法をご案内します。',
    badge: '買い目',
    headline: '買い目は「軸の候補」としてもお使いいただけます',
    body: [
      'メインレースの買い目は「本命 → 相手 5 頭」の馬単 5 点です。',
      '',
      'そのままお使いいただくこともできますし、',
      '本命だけを参考にして相手をご自身で選ぶ、という使い方もされています。',
      '',
      '点数を広げて当てにいくのではなく、軸を決めて絞る作り方をしています。',
    ],
    benefitTitle: '使い方の例',
    benefitItems: ['5 点をそのまま使う', '本命だけ参考にする', '相手から不要馬を除く'],
    ctaLabel: '今日の買い目を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 10, delayDays: 6, angle: '成績の確認',
    name: '結果の見方',
    subject: '【KEIBA Analytics】当たった日も外した日も残しています',
    preheader: '前日の買い目と結果を並べて公開しています。判断の材料にしてください。',
    badge: '結果',
    headline: '結果はそのまま残しています',
    body: [
      '前日に配信した買い目と、その結果を並べて公開しています。',
      '',
      '当たった日だけを見せると判断の material になりません。',
      '外した日もそのまま残しているので、ご自身の目で確かめてください。',
      '',
      '数字はページのものが最新です。メールには書き写していません。',
    ],
    benefitTitle: '結果ページで見られるもの',
    benefitItems: ['前日のメインレース買い目', '的中・不的中', '払戻（的中時）'],
    ctaLabel: '前日の結果を見る',
    ctaUrl: `${SITE}/results-showcase/nankan/`,
    ctaNote: '実際の記録はこちらのページが最新です。',
  }),
  step({
    n: 11, delayDays: 6, angle: '不安の解消',
    name: 'よくあるご質問',
    subject: '【KEIBA Analytics】無料期間についてよくいただくご質問',
    preheader: '自動課金はありません。終了後の扱いもご案内します。',
    badge: 'ご質問',
    headline: 'よくいただくご質問',
    body: [
      'Q. 無料期間が終わったら自動で課金されますか',
      'A. されません。お手続きをいただかない限り料金は発生しません。',
      '',
      'Q. 期間が終わったらどうなりますか',
      'A. 無料予想と前日の結果ページは引き続きご覧いただけます。',
      '',
      'Q. 配信を止めたい',
      'A. このメール下部のリンクからいつでも止められます。',
    ],
    benefitTitle: '無料期間について',
    benefitItems: ['自動課金なし', 'お手続き不要', 'いつでも配信停止可'],
    ctaLabel: '予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間の終了日: ${EXPIRY}`,
  }),
  step({
    n: 12, delayDays: 6, angle: 'Premium との差',
    name: '見られる範囲の違い',
    subject: '【KEIBA Analytics】プランごとにご覧いただける範囲',
    preheader: 'Lightはメインレース。Premiumは全会場の有料予想です。',
    badge: '範囲',
    headline: 'ご覧いただける範囲の違い',
    body: [
      'いまお使いいただいている Light は、各開催のメインレースが対象です。',
      '',
      'Premium は中央（JRA）・南関の有料予想を全会場でご覧いただけます。',
      'メインレース以外も見たい場合はこちらになります。',
      '',
      'メインレースだけで十分という方は、いまのままで問題ありません。',
    ],
    benefitTitle: '違い',
    benefitItems: ['Light … 各開催のメインレース', 'Premium … 全会場の有料予想', '無料予想はどちらでも利用可'],
    ctaLabel: 'プランと料金を見る',
    ctaUrl: `${SITE}/pricing/`,
    ctaNote: '金額と内容はこちらのページが最新です。',
  }),
  step({
    n: 13, delayDays: 6, angle: '期間の確認',
    name: '期間の折り返し',
    subject: '【KEIBA Analytics】無料期間の残りについて',
    preheader: '終了日をあらためてご案内します。お手続きは不要です。',
    badge: '期間',
    headline: '無料期間の残りをお知らせします',
    body: [
      'Lightプランの無料期間について、終了日をあらためてご案内します。',
      '',
      '終了日は下部に記載しています。',
      '終了後に自動で課金されることはありません。',
      '',
      'まだご覧になっていない日があれば、この機会にお試しください。',
    ],
    benefitTitle: '期間中にできること',
    benefitItems: ['メインレースの買い目', '前日の結果との突き合わせ', 'AI総合指数と役割'],
    ctaLabel: '予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間の終了日: ${EXPIRY}`,
  }),
  step({
    n: 14, delayDays: 7, angle: '活用例',
    name: '指数と役割',
    subject: '【KEIBA Analytics】AI総合指数と役割の関係',
    preheader: '本命・対抗・単穴・連下。役割がどう決まるかをご案内します。',
    badge: '指数',
    headline: '指数と役割の関係',
    body: [
      '各馬には AI総合指数と役割（本命・対抗・単穴・連下など）が付いています。',
      '',
      '役割は指数だけで決まるわけではなく、',
      '過去の走りや騎手・条件との相性なども合わせて振り分けています。',
      '',
      '指数が近い馬でも役割が違うことがあります。その差が買い目に出ます。',
    ],
    benefitTitle: '見ておくと分かりやすい点',
    benefitItems: ['同じレース内での指数の並び', '役割の振り分け', '外している馬の扱い'],
    ctaLabel: '指数の並びを見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間中はお手続きなくご覧いただけます。${EXPIRY}`,
  }),
  step({
    n: 15, delayDays: 7, angle: '習慣化',
    name: '見なかった日',
    subject: '【KEIBA Analytics】見られない日があっても大丈夫です',
    preheader: '結果ページであとから追いかけられます。',
    badge: '続け方',
    headline: '毎日見られなくても構いません',
    body: [
      '毎日ご覧いただく必要はありません。',
      '',
      '見られなかった日も、翌日の結果ページで買い目と結果を確認できます。',
      'あとからまとめて見ていただく形でも、判断の材料になります。',
      '',
      '週末だけ、平日だけ、という使い方もされています。',
    ],
    benefitTitle: 'あとから追う方法',
    benefitItems: ['前日の買い目と結果', '的中・不的中の記録', '会場ごとの一覧'],
    ctaLabel: '結果を見る',
    ctaUrl: `${SITE}/results-showcase/jra/`,
    ctaNote: '記録はこちらのページが最新です。',
  }),
  step({
    n: 16, delayDays: 7, angle: '料金の考え方',
    name: '料金の考え方',
    subject: '【KEIBA Analytics】料金についての考え方',
    preheader: '金額はページに記載しています。判断はご自身のペースで。',
    badge: '料金',
    headline: '料金についてのご案内',
    body: [
      '有料プランの金額と内容は料金ページに記載しています。',
      '',
      'メールに金額を書くと、変更があったときにズレてしまうため、',
      '正確な内容はページでご確認ください。',
      '',
      '無料期間中に判断していただく必要はありません。',
      '終了後も無料予想はご覧いただけます。',
    ],
    benefitTitle: 'ご確認いただける場所',
    benefitItems: ['プランごとの内容', '金額', 'お支払い方法'],
    ctaLabel: 'プランと料金を見る',
    ctaUrl: `${SITE}/pricing/`,
    ctaNote: '金額と内容はこちらのページが最新です。',
  }),
  step({
    n: 17, delayDays: 7, angle: '不安の解消',
    name: '配信について',
    subject: '【KEIBA Analytics】配信の頻度と止め方について',
    preheader: '配信は下部のリンクからいつでも止められます。',
    badge: '配信',
    headline: '配信についてのご案内',
    body: [
      'このご案内は、無料期間をお使いいただいている方へお送りしています。',
      '',
      '短い間隔で何通も届かないよう、送る回数には上限を設けています。',
      '',
      '不要な場合は、このメール下部のリンクからいつでも止められます。',
      '止めても、サイトのご利用には影響しません。',
    ],
    benefitTitle: 'お知らせしておきたいこと',
    benefitItems: ['配信はいつでも停止できる', '停止してもサイトは使える', '自動課金はない'],
    ctaLabel: '予想を見る',
    ctaUrl: `${SITE}/dashboard/`,
    ctaNote: `無料期間の終了日: ${EXPIRY}`,
  }),
  step({
    n: 18, delayDays: 7, angle: '成績の確認',
    name: '結果の続き',
    subject: '【KEIBA Analytics】直近の買い目と結果',
    preheader: '前日ぶんの買い目と結果を公開しています。',
    badge: '結果',
    headline: '直近の記録をご覧いただけます',
    body: [
      '前日のメインレースについて、配信した買い目と結果を公開しています。',
      '',
      '当たった日も外した日も同じ形で残しています。',
      '数字はページのものが最新です。',
      '',
      'ご自身の見立てと突き合わせながらご覧ください。',
    ],
    benefitTitle: '結果ページ',
    benefitItems: ['南関の記録', '中央の記録', '的中時の払戻'],
    ctaLabel: '前日の結果を見る',
    ctaUrl: `${SITE}/results-showcase/nankan/`,
    ctaNote: '記録はこちらのページが最新です。',
  }),
  step({
    n: 19, delayDays: 7, angle: '期限前',
    name: '期間の終了が近い方へ',
    subject: '【KEIBA Analytics】無料期間の終了日について',
    preheader: '終了日をご案内します。お手続きは不要です。',
    badge: '期間',
    headline: '無料期間の終了日をご案内します',
    body: [
      'Lightプランの無料期間の終了日をご案内します。',
      '',
      '終了後に自動で課金されることはありません。お手続きも不要です。',
      '',
      '終了後は、無料予想と前日の結果ページを引き続きご覧いただけます。',
      'メインレースの買い目を続けてご覧になりたい場合は、料金ページをご確認ください。',
    ],
    benefitTitle: '終了後について',
    benefitItems: ['自動課金なし', '無料予想は継続', '結果ページも継続'],
    ctaLabel: 'プランと料金を見る',
    ctaUrl: `${SITE}/pricing/`,
    ctaNote: `無料期間の終了日: ${EXPIRY}`,
  }),
  step({
    n: 20, delayDays: 7, angle: '期限後',
    name: '期間終了後のご案内',
    subject: '【KEIBA Analytics】無料期間の終了後にご覧いただけるもの',
    preheader: '無料予想と結果ページは引き続きご利用いただけます。',
    badge: '終了後',
    headline: '無料期間が終わったあとも',
    body: [
      '無料期間が終わったあとも、次のものは引き続きご覧いただけます。',
      '',
      '・無料予想',
      '・前日のメインレース買い目と結果（実績ページ）',
      '',
      'メインレースの買い目を毎日ご覧になりたい場合は、',
      '料金ページからプランをご確認ください。',
    ],
    benefitTitle: '引き続きご利用いただけるもの',
    benefitItems: ['無料予想', '前日の買い目と結果', 'AI総合指数の考え方'],
    ctaLabel: 'プランの内容を確認する',
    ctaUrl: `${SITE}/pricing/`,
    ctaNote: '金額と内容はこちらのページが最新です。',
  }),
  step({
    n: 21, delayDays: 10, angle: '活用例',
    name: '無料予想の使い方',
    subject: '【KEIBA Analytics】無料予想の使い方',
    preheader: '無料の範囲でも、指数と役割の考え方はご覧いただけます。',
    badge: '無料予想',
    headline: '無料の範囲でご覧いただけるもの',
    body: [
      '無料予想でも、AI総合指数と役割の考え方はご覧いただけます。',
      '',
      '有料の範囲との違いは「どのレースまで見られるか」です。',
      '考え方そのものは同じものを使っています。',
      '',
      'まず無料予想でご覧いただき、必要になったら範囲を広げる形で構いません。',
    ],
    benefitTitle: '無料でご覧いただけるもの',
    benefitItems: ['無料予想のページ', '前日の結果', '指数と役割の考え方'],
    ctaLabel: '無料予想を見る',
    ctaUrl: `${SITE}/free-prediction/nankan/`,
    ctaNote: 'お手続きなくご覧いただけます。',
  }),
  step({
    n: 22, delayDays: 10, angle: 'comeback',
    name: 'しばらくご覧になっていない方へ',
    subject: '【KEIBA Analytics】最近の予想と結果',
    preheader: '直近の記録を公開しています。ご都合のよいときにご覧ください。',
    badge: 'お知らせ',
    headline: '直近の記録を公開しています',
    body: [
      'しばらくご覧になっていない方へ、直近の状況をお知らせします。',
      '',
      '前日のメインレース買い目と結果は、毎日そのまま公開しています。',
      '当たった日も外した日も残しているので、いまの状態を確かめられます。',
      '',
      'ご都合のよいときにご覧ください。',
    ],
    benefitTitle: 'ご覧いただけるもの',
    benefitItems: ['直近の買い目と結果', '南関・中央の両方', '無料予想'],
    ctaLabel: '直近の結果を見る',
    ctaUrl: `${SITE}/results-showcase/nankan/`,
    ctaNote: '記録はこちらのページが最新です。',
  }),
  step({
    n: 23, delayDays: 14, angle: '継続の提案',
    name: '続けてご覧になる場合',
    subject: '【KEIBA Analytics】続けてご覧になる場合のご案内',
    preheader: 'プランの内容と金額は料金ページに記載しています。',
    badge: 'ご案内',
    headline: '続けてご覧になる場合',
    body: [
      'メインレースの買い目を続けてご覧になりたい場合は、',
      '料金ページからプランをご確認ください。',
      '',
      '内容と金額はページに記載しています。',
      '',
      'いまは必要ない、という場合はこのままで問題ありません。',
      '無料予想と結果ページは引き続きご利用いただけます。',
    ],
    benefitTitle: 'ご確認いただける場所',
    benefitItems: ['プランごとの内容', '金額', 'お支払い方法'],
    ctaLabel: 'プランと料金を見る',
    ctaUrl: `${SITE}/pricing/`,
    ctaNote: '金額と内容はこちらのページが最新です。',
  }),
  step({
    n: 24, delayDays: 14, angle: 'comeback',
    name: '最後のご案内',
    subject: '【KEIBA Analytics】この一連のご案内は今回で最後です',
    preheader: '今後は通常のお知らせのみをお送りします。',
    badge: 'お知らせ',
    headline: 'この一連のご案内は今回で最後です',
    body: [
      'Lightプランの無料体験に関する一連のご案内は、今回で最後です。',
      '',
      '今後は通常のお知らせのみをお送りします。',
      '',
      '無料予想と前日の結果ページは、これまでどおりご覧いただけます。',
      'ご不要であれば、下部のリンクから配信を止められます。',
    ],
    benefitTitle: '引き続きご利用いただけるもの',
    benefitItems: ['無料予想', '前日の買い目と結果'],
    ctaLabel: '無料予想を見る',
    ctaUrl: `${SITE}/free-prediction/nankan/`,
    ctaNote: 'お手続きなくご覧いただけます。',
    footerNote: 'この一連のご案内は今回で最後です。今後は通常のお知らせのみをお送りします。',
  }),
]);

export default LIGHT_TRIAL_EXTRA_STEPS;
